text = input('Type something: ')
print('The primitive type of this value is ', type(text))
print('Does it contain only spaces? ', text.isspace())
print('Is numeric?', text.isnumeric())
print('Is alphabetic?', text.isalpha())
print('Is alphanumeric?', text.isalnum())
print('Is uppercase?', text.isupper())
print('Is lowercase?', text.islower())
print('Is title case?', text.istitle())
